# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create(name: "Soulfuric Trax T-Shirt", description: "Soulfuric is one of the most renowned labels in House music worldwide. Founded by Brian Tappert and Marc Pomeroy, who released under guises including Jazz-N-Groove, Urban Blues Project and Soulsearcher, it released material across Soulfuric Recordings and its equally influential Soulfuric Deep and Soulfuric Trax imprints from artists such as Cleptomaniacs, Axwell, Copyright, and Ron Carroll, to name just a few. This black crew neck T-shirt is made with super soft, jersey cotton. It features the Soulfuric Trax logo on the chest as a high-quality print. This T-shirt has strong seams, twin needle stitched hem and cuffs, and a woven logo label at the base, featuring the 4 To The Floor logo. The T-shirt is made of 100% cotton. The 4 To The Floor Apparel range showcases iconic house music labels, both past and present. Produced by an established fashion design team based in Shoreditch, London. All garments and fabrics are sourced and manufactured in England, Turkey and Portugal from leading suppliers to some of the world's most successful fashion brands.", price: 25, image_url: "products/tee_soulfurictrax.jpg", colour: "Black")
Product.create(name: "Nu Groove Recordings White / Red T-Shirt", description: "Legendary New York label that launched in 1988 and was a pre-cursor to all of the great New York house music record labels that followed. Run by Frank and Karen Mendez between, the label was initially founded to release music by the Burrell twins, Rheji & Ronald, but soon went from strength to strength, putting a number of genre-defining anthems ranging from ultra-deep and minimal house, through smooth soulful garage, to manic ravers’ delights. All brought together that cool New York sensibility. This standard fit, crew neck t-shirt in white cotton, features the striking ‘NUGROOVE’ logo print in red screen print across the chest. It is a standard fit t-shirt in 100% high quality, supersoft cotton. This garment has strong seams, twin needle stitched hem and armholes. Woven logo label at base, featuring the 4 To The Floor logo. The 4 To The Floor Apparel range showcases iconic house music labels, both past and present. Produced by an established fashion design team based in Shoreditch, London. All garments and fabrics are sourced and manufactured in England, Turkey and Portugal from leading suppliers to some of the world's most successful fashion brands.", price: 25, image_url: "products/tee_nugroove_whitered.jpg", colour: "White")
Product.create(name: "Defected / Sound Wave Beach Shorts", description: "Brand new for S/S17, following last year’s introduction of green DEFECTED logo shorts which were worn by household DJs, Sonny Fodera, Franky Rizardo, etc… We’ve responded to public popular demand and Defected again has collaborated with Swimwear aficionados Boardies® to create these limited edition shorts. The high quality, aqua blue Boardies® swimshorts, featuring the ‘DEFECTED‘ logo, are made from supersoft, lightweight material, these elasticated designer shorts are a quick-drying wonder, perfect for dressing up or down for the occasion. Featuring Boardies® mesh lining support, two side pockets, and a Velcro back pocket sporting our laser cut woven Boardies® label logo. Plus, they come in their own branded drawstring bag for safekeeping on the go.", price: 50, image_url: "products/shorts_blue.jpg", colour: "Aqua")
Product.create(name: "Defected Logo Beach Towel / Hamman", description: "New for S/S17 - The best beach accessory you’ll ever own, a hammam is made from 100% high quality cotton and they are quick drying and compact, and double up as both a beach towel and sarong. Specially sourced in Turkey, this product has been hand woven with the DEFECTED logo in an indigo blue/stone white combination, using the finest absorbent cotton.", price: 22, image_url: "products/towel.jpg", colour: "Navy")
